# Generated by Django 6.0.3 on 2026-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='monthly_budget',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
